export enum ActionType {
    LOG_IN_REQUEST = "LOG_IN_REQUEST",
    LOG_IN_SUCCESS = "LOG_IN_SUCCESS",
    LOG_IN_FAIL = "LOG_IN_FAIL",
    LOG_OUT = "LOG_OUT",
    SIGN_UP_REQUEST = "SIGN_UP_REQUEST",
    SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
    SIGN_UP_FAIL = "SIGN_UP_FAIL",
    ADD_RECIPE = "ADD_RECIPE",
    DELETE_RECIPE = "DELETE_RECIPE",
    FETCH_RECIPES_REQUEST = "FETCH_RECIPES_REQUEST",
    FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL"
}
