export enum ActionType {
    LOG_IN = "LOG_IN",
    LOG_OUT = "LOG_OUT",
    ADD_RECIPE = "ADD_RECIPE",
    DELETE_RECIPE = "DELETE_RECIPE",
    FETCH_RECIPES_REQUEST = "FETCH_RECIPES_REQUEST",
    FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL"
}
